from app.analysis.ruff_runner import RuffRunner
from app.analysis.bandit_runner import BanditRunner
from app.llm.reviewer import LLMReviewer

class Aggregator:
    def __init__(self):
        self.ruff = RuffRunner()
        self.bandit = BanditRunner()
        self.llm = LLMReviewer(api_key=None)

    def analyze_pr(self, files: list) -> str:
        all_findings = []

        for file_obj in files:
            filename = file_obj['filename']
            all_findings.extend(self.ruff.analyze(filename))
            all_findings.extend(self.bandit.analyze(filename))

        llm_result = self.llm.review_diff("dummy_diff")

        report = []
        report.append("# Code Review Bot Report")
        report.append(f"_{llm_result['summary']}_")
        
        if all_findings:
            report.append("\n### Static Analysis Findings")
            for f in all_findings:
                report.append(f.to_markdown())
        else:
            report.append("\n### Static Analysis passed!")

        report.append("\n### AI Insights")
        for comment in llm_result['comments']:
            report.append(f"- **{comment['file']}** (L{comment['line']}): {comment['text']}")

        report.append("\n---\n*Generated by Code Review Bot*")
        
        return "\n".join(report)