from app.analysis.ruff_runner import RuffRunner
from app.analysis.bandit_runner import BanditRunner
from app.llm.reviewer import LLMReviewer

class Aggregator:
    def __init__(self):
        self.ruff = RuffRunner()
        self.bandit = BanditRunner()
        self.llm = LLMReviewer(api_key=None)

    def analyze_pr(self, files: list) -> dict:
        """
        Returns a dictionary with 'summary_text' and 'inline_comments'
        """
        all_findings = []
        
        # 1. Run Static Analysis
        for file_obj in files:
            filename = file_obj['filename']
            all_findings.extend(self.ruff.analyze(filename))
            all_findings.extend(self.bandit.analyze(filename))

        # 2. Run LLM
        allowed_filenames = [f['filename'] for f in files]
        llm_result = self.llm.review_diff("dummy_diff", allowed_filenames)
        llm_comments = llm_result['comments']
        
        # 3. Combine everything
        total_findings = all_findings + llm_comments
        
        # 4. Prepare Inline Comments (High/Medium severity only)
        inline_comments = []
        summary_items = []
        
        for f in total_findings:
            # Inline comment logic: Must have a line number and be important
            if f.line > 0 and f.severity in ["high", "medium"]:
                inline_comments.append({
                    "path": f.file,
                    "line": f.line,
                    "body": f"**[{f.tool.upper()}]** {f.message}\n_Suggestion: {f.category}_"
                })
            else:
                summary_items.append(f)

        # 5. Build Markdown Summary (Only for things NOT posted inline)
        report = []
        report.append(f"#Code Review Bot Report")
        report.append(f"_{llm_result['summary']}_")
        
        if inline_comments:
            report.append(f"\n### Posted {len(inline_comments)} Inline Comments")
            report.append("_Check the 'Files Changed' tab for detailed review._")

        if summary_items:
            report.append("\n### Other Findings")
            for f in summary_items:
                report.append(f.to_markdown())

        report.append("\n---\n*Generated by Code Review Bot*")
        
        return {
            "summary_text": "\n".join(report),
            "inline_comments": inline_comments
        }